apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-node
  template:
    metadata:
      labels:
        app: redis-node
    spec:
      containers:
      - name: redis-node
        image: redis-node:local
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_URL
          value: redis://redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-node
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
  selector:
    app: redis-node